data_cfg:
  dataset_name: CASIA-B
  dataset_root: CASIA-B-pkl
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitSet
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: OdeNet
  in_channels:
    - 1
    - 16
    - 32
    - 64
    - 1
    - 64
  SeparateFC1:
    in_channels: 64
    out_channels: 256
    parts_num: 64
  SeparateFC2:
    in_channels: 256
    out_channels: 128
    parts_num: 64
  SeparateFC3:
    in_channels: 64
    out_channels: 256
    parts_num: 64
  SeparateFC4:
    in_channels: 256
    out_channels: 74
    parts_num: 64
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 10000
    - 20000
    - 30000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  log_iter: 5
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5
  save_name: GaitSet
  sync_BN: false
  total_iter: 20
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_unordered
    type: TripletSampler
